homework_2
boodscode237/machine_learning_for_analysis_scientific_data_homeworks pull request #1
Opened 2023-12-14 00:46 UTC by boodscode237

Dataset can be founded in Kaggle

2023-12-23 11:31 UTC, boodscode237 commented
Это домашнее задание по Machine Learning For analysis of scientific data. я не знал как его задать на проверку. я сделал все в срок и вот такая структура. первое домашнее задание на главной ветке второе домашнее задание  на ветке homework_2 он находится в папке notebooks.

2023-12-27 19:01 UTC, pacifikus requested changes
Добрый день!

Оставлю комментарии сразу ко всем ДЗ, чтобы было целостное понимание

Комментарии по ДЗ 1:

- Обоснование для метрики нужно приводить в самом начале до проведения экспериментов, пока получается, что вы измеряли в моделях accuracy, считали ее на кросс-валидации, подбирали гиперпараметры, а потом в конце неожиданно говорите, что смотреть надо на recall... Получается, все прошлые эксперименты бесполезны с точки зрения новой метрики...
- Недостает комментариев к графикам - что на них можно увидеть? Почему вы решили посмотреть именно эти распределения/признаки/отношения?

В целом в этом дз не требовалось обучать модели, но раз эта часть есть, оставлю несколько комментариев:
- В `train_test_split` тоже нужно фиксировать `random_state` в аргументах
- В `RandomForestClassifier` также нужно фиксировать `random_state`
- `RandomizedSearchCV` также нужно фиксировать `random_state`

И в целом эта работа почти полностью повторяет [ноутбук](https://github.com/Aahra/End-to-End-Heart-Disease-classification-Milestone-Project-1-/blob/main/End_to_end_Heart_disease_classification_.ipynb)

Комментарии по ДЗ 2:

- Не очень понятно, почему меняется датасет в ДЗ 2 - предполагалось, что на протяжении всех трех ДЗ будет использоваться один и тот же набор данных
- Опять же тогда всплывают моменты из ДЗ 1 - почему мы используем тут именно RMSLE? 
- В этой работе по заданию нужно использовать какую-то "простую" модель, то есть не ансамбль, а RandomForestRegressor - как раз ансамбль

И еще эта работа почти полностью повторяет [ноутбук](https://www.kaggle.com/code/amalap862001/end-to-end-bulldozer-price-regression-project)

2023-12-27 19:35 UTC, boodscode237 commented
Я переделаю его, используя первый набор данных(heart-disease). Для второго набора данных в конкурсе было указано использовать именно его.

2023-12-28 19:02 UTC, boodscode237 commented
And also, the code I sent previously was case studies of a Udemy course I am taking.

2024-01-12 17:52 UTC, closed without merging